import { PermissionConst, RoleConst } from '@/utils/permission/data'

const financeRouter = {
  path: '/finance',
  name: 'finance',
  meta: {
    title: 'views.finance.title',
    menu: true,
    permission: [
      RoleConst.USER.getWorkspaceRole,
      RoleConst.WORKSPACE_MANAGE.getWorkspaceRole,
      PermissionConst.FINANCE_READ.getWorkspacePermission,
      PermissionConst.FINANCE_READ.getWorkspacePermissionWorkspaceManageRole,
    ],
    icon: 'app-finance',
    iconActive: 'app-finance-active',
    group: 'workspace',
    order: 1.5,
  },
  redirect: '/finance/overview',
  component: () => import('@/layout/layout-template/MainLayout.vue'),
  children: [
    {
      path: '/finance/overview',
      name: 'finance-overview',
      meta: {
        icon: 'app-agent',
        iconActive: 'app-agent-active',
        title: 'views.finance.overview',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-overview',
        order: 1,
      },
      component: () => import('@/views/finance/overview/index.vue'),
    },
    {
      path: '/finance/project',
      name: 'finance-project',
      meta: {
        icon: 'app-knowledge',
        iconActive: 'app-knowledge-active',
        title: 'views.finance.project.title',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-project',
        order: 2,
      },
      component: () => import('@/views/finance/project/index.vue'),
    },
    {
      path: '/finance/project/:pk',
      name: 'finance-project-detail',
      meta: {
        title: 'views.finance.project.title',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-project',
        hidden: true,
      },
      component: () => import('@/views/finance/project/detail.vue'),
    },
    {
      path: '/finance/materials',
      name: 'finance-materials',
      meta: {
        icon: 'app-document',
        iconActive: 'app-document-active',
        title: 'views.finance.materials',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-materials',
        order: 3,
      },
      component: () => import('@/views/finance/materials/index.vue'),
    },
    {
      path: '/finance/documents',
      name: 'finance-documents',
      meta: {
        icon: 'app-document',
        iconActive: 'app-document-active',
        title: 'views.finance.documents',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-documents',
        order: 4,
      },
      component: () => import('@/views/finance/documents/index.vue'),
    },
    {
      path: '/finance/feasibility',
      name: 'finance-feasibility',
      meta: {
        icon: 'app-magnify',
        iconActive: 'app-magnify',
        title: 'views.finance.feasibility',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-feasibility',
        order: 5,
        disabled: true,
      },
      component: () => import('@/views/finance/feasibility/index.vue'),
    },
    {
      path: '/finance/progress',
      name: 'finance-progress',
      meta: {
        icon: 'app-operation',
        iconActive: 'app-operation',
        title: 'views.finance.progress',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-progress',
        order: 6,
        disabled: true,
      },
      component: () => import('@/views/finance/progress/index.vue'),
    },
    {
      path: '/finance/intel',
      name: 'finance-intel',
      meta: {
        icon: 'app-sync',
        iconActive: 'app-sync',
        title: 'views.finance.intel',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-intel',
        order: 7,
        disabled: true,
      },
      component: () => import('@/views/finance/intel/index.vue'),
    },
    {
      path: '/finance/template',
      name: 'finance-template',
      meta: {
        icon: 'app-copy',
        iconActive: 'app-copy',
        title: 'views.finance.template',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-template',
        order: 8,
      },
      component: () => import('@/views/finance/template/index.vue'),
    },
    {
      path: '/finance/audit',
      name: 'finance-audit',
      meta: {
        icon: 'app-lock',
        iconActive: 'app-lock',
        title: 'views.finance.audit',
        activeMenu: '/finance',
        parentPath: '/finance',
        parentName: 'finance',
        sameRoute: 'finance-audit',
        order: 9,
      },
      component: () => import('@/views/finance/audit/index.vue'),
    },
  ],
}

export default financeRouter
