<template>
  <div v-loading="loading" class="docx-preview">
    <!--
      Disclaimer banner —— mammoth 把 docx 转成 *语义* HTML，自定义样式 / 页眉
      页脚 / 分页 / 复杂表格合并都会被剥离。用户经常以为预览缩水了，
      实际上下载 .docx 才是完整的渲染结果。
    -->
    <el-alert
      type="info"
      :closable="false"
      show-icon
      class="docx-preview__banner"
    >
      <template #title>
        <span>{{ $t('views.finance.documentsLib.previewDisclaimer.banner') }}</span>
      </template>
      <template #default>
        <el-button
          v-if="generationId"
          type="primary"
          size="small"
          :loading="downloading"
          class="docx-preview__dl-btn"
          @click="onDownload"
        >
          <AppIcon iconName="app-download" class="mr-4" />
          {{ $t('views.finance.documentsLib.previewDisclaimer.download') }}
        </el-button>
      </template>
    </el-alert>

    <!--
      Security note: this v-html sink is intentional. The HTML originates from
      server-side mammoth.js rendering of a docx generated by MaxKB itself
      (template + placeholder values, both validated server-side). It is
      therefore treated as trusted. Do NOT expand v-html usage to render
      user-supplied HTML elsewhere without an explicit sanitisation step.
    -->
    <div class="docx-preview__content" v-html="html"></div>
    <div v-if="!loading && !html" class="docx-preview__empty">
      {{ $t('common.noData') }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { fetchPreview, downloadGeneration } from '@/api/finance/generation'

interface Props {
  workspaceId: string
  generationId: string
}

const props = defineProps<Props>()

const html = ref('')
const loading = ref(false)
const downloading = ref(false)

async function load() {
  if (!props.workspaceId || !props.generationId) {
    html.value = ''
    return
  }
  loading.value = true
  try {
    const res = await fetchPreview(props.workspaceId, props.generationId)
    html.value = res?.data?.html ?? ''
  } catch {
    html.value = ''
  } finally {
    loading.value = false
  }
}

async function onDownload() {
  if (!props.workspaceId || !props.generationId) return
  downloading.value = true
  try {
    // Content-Disposition 头里有真实文件名；这里 fallback 仅在头缺失时生效
    await downloadGeneration(
      props.workspaceId,
      props.generationId,
      `${props.generationId}.docx`,
    )
  } finally {
    downloading.value = false
  }
}

onMounted(load)
watch(() => props.generationId, load)
watch(() => props.workspaceId, load)
</script>

<style lang="scss" scoped>
.docx-preview {
  max-height: 70vh;
  overflow-y: auto;
  padding: 24px;
  background: #fff;
  font-family: 'Microsoft YaHei', 'PingFang SC', sans-serif;
  line-height: 1.8;
  color: var(--el-text-color-primary);

  &__banner {
    margin-bottom: 16px;
  }
  &__dl-btn {
    margin-top: 6px;
  }

  &__empty {
    text-align: center;
    color: var(--el-text-color-secondary);
    padding: 48px 0;
  }

  &__content :deep(table) {
    border-collapse: collapse;
    width: 100%;
    margin: 8px 0;
  }
  &__content :deep(td),
  &__content :deep(th) {
    border: 1px solid #dcdfe6;
    padding: 4px 8px;
    vertical-align: top;
  }
  &__content :deep(h1),
  &__content :deep(h2),
  &__content :deep(h3) {
    margin-top: 1em;
    margin-bottom: 0.4em;
    font-weight: 600;
  }
  &__content :deep(p) {
    margin: 0.4em 0;
  }
  &__content :deep(img) {
    max-width: 100%;
  }
}
</style>
